const humanPhotos = [
  {
    photo: "/KennyAuraFarming.jpg",
    category: "Human",
    name: "Blud think he's an aura farmer",
  },
  { photo: "/TheBoys.jpg", category: "Human", name: "The Boys" },
  { photo: "/CardinStairs.jpg", category: "Human", name: "Cardin" },
  {
    photo: "/NavidAuraFarming.jpg",
    category: "Human",
    name: "Bro IS an aura farmer",
  },
  { photo: "/PersonOnStairs.jpg", category: "Human", name: "Cardin" },
  { photo: "/NavidFlex.jpg", category: "Human", name: "Navid big boy" },
  { photo: "/Brian.jpg", category: "Human", name: "Brian" },
  { photo: "/TroyMewing.jpg", category: "Human", name: "Troy Mewing" },
  {
    photo: "/SeabassAuraFarming.jpg",
    category: "Human",
    name: "Seabass Aura Farming",
  },
  {
    photo: "/TimothyAuraFarming.jpg",
    category: "Human",
    name: "Timothy Aura Farming",
  },
  {
    photo: "/NasirAndAarnav.jpg",
    category: "Human",
    name: "Nasir Aura Farming",
  },
  { photo: "/TimoandCardin.jpg", category: "Human", name: "Timo and Cardin" },
  { photo: "/Kris8Ball.jpg", category: "Human", name: "Kris" },
  { photo: "/Aarnav8Ball.jpg", category: "Human", name: "Aarnav" },
  { photo: "/SickShot.jpg", category: "Human", name: "Sick Shot" },
  { photo: "/Troy.jpg", category: "Human", name: "Troy" },
  { photo: "/Emily.jpg", category: "Human", name: "Sick Shot" },
  { photo: "/Kris8Ball2.jpg", category: "Human", name: "Kris" },
  { photo: "/Sai.jpg", category: "Human", name: "Sai" },
  { photo: "/SickShot.jpg", category: "Human", name: "Sick Shot" },
  { photo: "/Ronald.jpg", category: "Human", name: "Ronald" },
  {
    photo: "/SeabassTheThinker.jpg",
    category: "Human",
    name: "Seabass the Thinker",
  },
  {
    photo: "/SeabassStanding.jpg",
    category: "Human",
    name: "Seabass Aura Farming",
  },
  { photo: "/DJ.jpg", category: "Human", name: "DJ" },
  { photo: "/NasirShot.jpg", category: "Human", name: "Nasir Shot" },
  {
    photo: "/NasirBackShot.jpg",
    category: "Human",
    name: "Nasir Back Shot (Pause)",
  },
  { photo: "/SeabassStanding2.jpg", category: "Human", name: "Seabass" },
  {
    photo: "/KrisAuraFarmingAarnav.jpg",
    category: "Human",
    name: "Kris Aura Farming Aarnav",
  },
  { photo: "/AarnavBasketball.jpg", category: "Human", name: "Aarnav" },
  { photo: "/AarnavLayup.jpg", category: "Human", name: "Aarnav Layup" },
  { photo: "/AarnavPole_2.jpg", category: "Human", name: "Aarnav Pole" },
  { photo: "/NasirMiles.jpg", category: "Human", name: "Nasir Miles!?!?!?" },
  { photo: "/AarnavPole_3.jpg", category: "Human", name: "Aarnav Pole" },
  { photo: "/AarnavPole.jpg", category: "Human", name: "Aarnav Pole" },
  { photo: "/AarnavShooting.jpg", category: "Human", name: "Aarnav Shot" },
  { photo: "/AarnavShot.jpg", category: "Human", name: "Aarnav Shot" },
  {
    photo: "/AuraFarmingTree.jpg",
    category: "Human",
    name: "Aura Farming Tree",
  },
  { photo: "/BasketballShot.jpg", category: "Human", name: "Basketball Shot" },
  {
    photo: "/NasirMiles_3.jpg",
    category: "Human",
    name: "Nasir Miles!?!?!?!?!",
  },
  { photo: "/BenShot.jpg", category: "Human", name: "Aarnav Pole" },
  { photo: "/DarkShot.jpg", category: "Human", name: "Ocean Cool" },
  { photo: "/NasirBoner.jpg", category: "Human", name: "Nasir" },
  { photo: "/NasirMiles_2.jpg", category: "Human", name: "NASIR MILES!?!?!?!" },
  {
    photo: "/NasirMilesJump.jpg",
    category: "Human",
    name: "Nasir SPIDER MAN!?!?!?",
  },
  { photo: "/SeabassBum.jpg", category: "Human", name: "Seabass Booty" },
  { photo: "/SeabassDead.jpg", category: "Human", name: "Seabass Dead" },
  {
    photo: "/SeabassPole.jpg",
    category: "Human",
    name: "Seabass Aura Farming Pole",
  },
  { photo: "/SeabassShot.jpg", category: "Human", name: "Seabass Shot" },
  { photo: "/TroyLayup.jpg", category: "Human", name: "Troy Layup" },
  { photo: "/TroyLayup2.jpg", category: "Human", name: "Troy Layup 2" },
  {
    photo: "/TroyNasir_2.jpg",
    category: "Human",
    name: "Troy and Nasir Aura Farming",
  },
  { photo: "/TroyPole.jpg", category: "Human", name: "Troy Pole Aura Farming" },
  { photo: "/TroyShot.jpg", category: "Human", name: "Troy Shot" },
];

export { humanPhotos };
