const miscPhotos = [
  {
    photo: "/CommHillRed.jpg",
    category: "Misc",
    name: "Communication Hill Street",
  },
  { photo: "/Shiba.jpg", category: "Misc", name: "Shiba!" },
  {
    photo: "/JapaneseBuilding.jpg",
    category: "Misc",
    name: "Japanese Tea Garden Architecture",
  },
  { photo: "/Jimmy.jpg", category: "Misc", name: "Jimmy 8-Ball" },
  { photo: "/Coke.jpg", category: "Misc", name: "Coke Ad" },
  { photo: "/1.jpg", category: "Misc", name: "1" },
  { photo: "/RedandWhite.jpg", category: "Misc", name: "Red and White Ball" },
  { photo: "/Katana.jpg", category: "Misc", name: "Katana" },
  { photo: "/Squirel.jpg", category: "Misc", name: "SQUIRELL" },
  { photo: "/MoreSquirel.jpg", category: "Misc", name: "MORE SQUIRELL" },
  { photo: "/JapaneseText.jpg", category: "Misc", name: "Japanese Excerpt" },
  { photo: "/Oversaturated.jpg", category: "Misc", name: "Too Green" },
  { photo: "/RedBuilding.jpg", category: "Misc", name: "Building" },
  { photo: "/JapanesePond.jpg", category: "Misc", name: "Pond" },
  { photo: "/CoolBuilding.jpg", category: "Misc", name: "Cool Building" },
  { photo: "/Symmetry.jpg", category: "Misc", name: "Symmetry" },
  { photo: "/CarLongExposure.jpg", category: "Misc", name: "Vroom" },
  { photo: "/SusBuild.jpg", category: "Misc", name: "Susalitoo so cool" },
  { photo: "/Monterey2025/Misc/3WindowTank.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/BeachPortrait2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/BeachPortrait3.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/BeachPortrait4.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/BigCircle.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird3.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird4.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird5.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird6.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird7.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird8.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird9.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird10.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird11.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird12.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird13.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird14.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird15.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird16.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird17.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird18.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird19.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird20.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird21.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird22.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Bird23.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Coast.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish1.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish3.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish4.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish5.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish6.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish7.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish8.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish9.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish10.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish11.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish12.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish13.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish14.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish15.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish16.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish17.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish18.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish19.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish20.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish21.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish22.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish23.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish24.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish25.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish26.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish27.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish28.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish29.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish30.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish31.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish32.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish33.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish34.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish35.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish36.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish37.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Fish38.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/FishExposition.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/HandonTank.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/HandonTank2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish3.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish4.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish5.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish6.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish7.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/JellyFish8.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter3.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter4.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter5.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter6.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter7.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter8.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter9.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter10.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Otter11.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Penguin.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Penguin2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Penguin3.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant3.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant4.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant5.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant6.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant7.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant8.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Plant9.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Roof.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Roof2.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/ScubaD.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Seashell.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/SmallThing.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/Spider.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/TimothyLandscape.jpg", category: "Misc", name: "" },
  { photo: "/Monterey2025/Misc/UpShot.jpg", category: "Misc", name: "" },
];

export { miscPhotos }
