const photos = [
    {photo: "/KennyAuraFarming.jpg", category: "Human", name: "Blud think he's an aura farmer"},
    {photo: "/TheBoys.jpg", category: "Human", name: "The Boys"},
    {photo: "/CardinStairs.jpg", category: "Human", name: "Cardin"},
    {photo: "/CarLongExposure.jpg", category: "Long Exposure", name: "Car look cool hehe"},
    {photo: "/NavidAuraFarming.jpg", category: "Human", name: "Bro IS an aura farmer"},
    {photo: "/CommHillRed.jpg", category: "Misc", name: "Communication Hill Street"},
    {photo: "/PersonOnStairs.jpg", category: "Human", name: "Cardin"},
    {photo: "/NavidFlex.jpg", category: "Human", name: "Navid big boy"},
    {photo: "/Brian.jpg", category: "Human", name: "Brian"},
    {photo: "/TroyMewing.jpg", category: "Human", name: "Troy Mewing"},
    {photo: "/SeabassAuraFarming.jpg", category: "Human", name: "Seabass Aura Farming"},
    {photo: "/Shiba.jpg", category: "Misc", name: "Shiba!"},
    {photo: "/SFStreet.jpg", category: "Car", name: "Street next to Golden Gate Park"},
    {photo: "/JapaneseBuilding.jpg", category: "Misc", name: "Japanese Tea Garden Architecture"},
    {photo: "/TimothyAuraFarming.jpg", category: "Human", name: "Timothy Aura Farming"},
    {photo: "/NasirAndAarnav.jpg", category: "Human", name: "Nasir Aura Farming"},
    {photo: "/BlackCar.jpg", category: "Car", name: "Subaru BRZ"},
    {photo: "/BlackCar2.jpg", category: "Car", name: "Subaru BRZ"},
    {photo: "/EpicCar.jpg", category: "Car", name: "Nissan Skyline GT-R R34"},
    {photo: "/EpicCar2.jpg", category: "Car", name: "Nissan Skyline GT-R R34"},
    {photo: "/GasStation.jpg", category: "Car", name: "Gas Station on Tully Rd"},
    {photo: "/RedCarEngine.jpg", category: "Car", name: "Engine"},
    {photo: "/RedCarReflect.jpg", category: "Car", name: "Red Car Cool :o"},
    {photo: "/BlueEngine.jpg", category: "Car", name: "Engine"},
    {photo: "/Engine2.jpg", category: "Car", name: "Engine"},
    {photo: "/GT-R-R33-Back.jpg", category: "Car", name: "Nissan GT-R R33"},
    {photo: "/GT-R-R33-Front.jpg", category: "Car", name: "Nissan GT-R R33"},
    {photo: "/GT-R-R33-FrontAngled.jpg", category: "Car", name: "Nissan GT-R R33"},
    {photo: "/HondaPreludeRed.jpg", category: "Car", name: "Honda Prelude"},
    {photo: "/Motorcycle.jpg", category: "Car", name: "Motorcycle"},
    {photo: "/MotorcycleAngle.jpg", category: "Car", name: "Motorcycle"},
    {photo: "/NissanBack.jpg", category: "Car", name: "Nissan GT-R R33"},
    {photo: "/NissanFrontAngle.jpg", category: "Car", name: "Nissan GT-R R33"},
    {photo: "/SteeringWheel.jpg", category: "Car", name: "Steering Wheel"},
    {photo: "/Wheel.jpg", category: "Car", name: "Wheel"},
    {photo: "/NissanWheelAngle.jpg", category: "Car", name: "Nissan GT-R R33"},
    {photo: "/NissanPortrait.jpg", category: "Car", name: "Nissan GT-R R33"},
    {photo: "/TimoandCardin.jpg", category: "Human", name: "Timo and Cardin"},
    {photo: "/Kris8Ball.jpg", category: "Human", name: "Kris"},
    {photo: "/CopCar.jpg", category: "Car", name: "Somebody getting slimed"},
    {photo: "/Aarnav8Ball.jpg", category: "Human", name: "Aarnav"},
    {photo: "/SickShot.jpg", category: "Human", name: "Sick Shot"},
    {photo: "/Troy.jpg", category: "Human", name: "Troy"},
    {photo: "/Emily.jpg", category: "Human", name: "Sick Shot"},
    {photo: "/Kris8Ball2.jpg", category: "Human", name: "Kris"},
    {photo: "/Sai.jpg", category: "Human", name: "Sai"},
    {photo: "/SickShot.jpg", category: "Human", name: "Sick Shot"},
    {photo: "/Ronald.jpg", category: "Human", name: "Ronald"},
    {photo: "/SeabassTheThinker.jpg", category: "Human", name: "Seabass the Thinker"},
    {photo: "/SeabassStanding.jpg", category: "Human", name: "Seabass Aura Farming"},
    {photo: "/RandomCar.jpg", category: "Car", name: "Random Car"},
    {photo: "/DJ.jpg", category: "Human", name: "DJ"},
    {photo: "/Jimmy.jpg", category: "Misc", name: "Jimmy 8-Ball"},
    {photo: "/Coke.jpg", category: "Misc", name: "Coke Ad"},
    {photo: "/1.jpg", category: "Misc", name: "1"},
    {photo: "/RedandWhite.jpg", category: "Misc", name: "Red and White Ball"},
    {photo: "/NasirShot.jpg", category: "Human", name: "Nasir Shot"},
    {photo: "/NasirBackShot.jpg", category: "Human", name: "Nasir Back Shot (Pause)"},
    {photo: "/Katana.jpg", category: "Misc", name: "Katana"},
    {photo: "/Squirel.jpg", category: "Misc", name: "SQUIRELL"},
    {photo: "/MoreSquirel.jpg", category: "Misc", name: "MORE SQUIRELL"},
    {photo: "/JapaneseText.jpg", category: "Misc", name: "Japanese Excerpt"},
    {photo: "/Oversaturated.jpg", category: "Misc", name: "Too Green"},
    {photo: "/RedBuilding.jpg", category: "Misc", name: "Building"},
    {photo: "/JapanesePond.jpg", category: "Misc", name: "Pond"},
    {photo: "/CoolBuilding.jpg", category: "Misc", name: "Cool Building"},
    {photo: "/Symmetry.jpg", category: "Misc", name: "Symmetry"},
    {photo: "/SeabassStanding2.jpg", category: "Human", name: "Seabass"},
    {photo: "/EmilyDriving.jpg", category: "Car", name: "Emily Driving to our Doom"},
    {photo: "/CarLongExposure.jpg", category: "Misc", name: "Vroom"},
    {photo: "/KrisAuraFarmingAarnav.jpg", category: "Human", name: "Kris Aura Farming Aarnav"},
    {photo: "/AarnavBasketball.jpg", category: "Human", name: "Aarnav"},
    {photo: "/AarnavLayup.jpg", category: "Human", name: "Aarnav Layup"},
    {photo: "/AarnavPole_2.jpg", category: "Human", name: "Aarnav Pole"},
    {photo: "/NasirMiles.jpg", category: "Human", name: "Nasir Miles!?!?!?"},
    {photo: "/AarnavPole_3.jpg", category: "Human", name: "Aarnav Pole"},
    {photo: "/AarnavPole.jpg", category: "Human", name: "Aarnav Pole"},
    {photo: "/AarnavShooting.jpg", category: "Human", name: "Aarnav Shot"},
    {photo: "/AarnavShot.jpg", category: "Human", name: "Aarnav Shot"},
    {photo: "/AuraFarmingTree.jpg", category: "Human", name: "Aura Farming Tree"},
    {photo: "/BasketballShot.jpg", category: "Human", name: "Basketball Shot"},
    {photo: "/NasirMiles_3.jpg", category: "Human", name: "Nasir Miles!?!?!?!?!"},
    {photo: "/BenShot.jpg", category: "Human", name: "Aarnav Pole"},
    {photo: "/CarSunset.jpg", category: "Car", name: "Car Sunset"},
    {photo: "/DarkShot.jpg", category: "Human", name: "Ocean Cool"},
    {photo: "/NasirBoner.jpg", category: "Human", name: "Nasir"},
    {photo: "/NasirMiles_2.jpg", category: "Human", name: "NASIR MILES!?!?!?!"},
    {photo: "/NasirMilesJump.jpg", category: "Human", name: "Nasir SPIDER MAN!?!?!?"},
    {photo: "/SeabassBum.jpg", category: "Human", name: "Seabass Booty"},
    {photo: "/SeabassDead.jpg", category: "Human", name: "Seabass Dead"},
    {photo: "/SeabassPole.jpg", category: "Human", name: "Seabass Aura Farming Pole"},
    {photo: "/SeabassShot.jpg", category: "Human", name: "Seabass Shot"},
    {photo: "/SusBuild.jpg", category: "Misc", name: "Susalitoo so cool"},
    {photo: "/TroyLayup.jpg", category: "Human", name: "Troy Layup"},
    {photo: "/TroyLayup2.jpg", category: "Human", name: "Troy Layup 2"},
    {photo: "/TroyNasir_2.jpg", category: "Human", name: "Troy and Nasir Aura Farming"},
    {photo: "/TroyPole.jpg", category: "Human", name: "Troy Pole Aura Farming"},
    {photo: "/TroyShot.jpg", category: "Human", name: "Troy Shot"},
  ];

  export { photos };